config/routes.rb
Rails.application.routes.draw do

  root 'tickets#new'
  resources :tickets
  

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base

  attr_accessor :date_par_défaut

#  def initialize(attributes = { date: Date.today })
#    @date = attributes[:date]
#  end

  def ht20
    @ht20 = (ttc20 / 1.2).round(2)
  end

  def ht5
    @ht5 = (ttc5 / 1.055).round(2)
  end

  def tva20
    @tva20 = ttc20 - ht20
  end

  def tva5
    @tva5 = ttc5 - ht5
  end


  def totalTTC
    @totalTTC = ttc20 + ttc5
  end

  def trou_de_caisse
    @trou_de_caisse = caisseréelle - totalTTC
  end

  def self.to_csv
    CSV.generate(:col_sep => ";") do |csv|
      all.each do |t|
        attributes = [:date, :numéro, :totalTTC, :ht5, :ht20, :tva5, :tva20, :trou_de_caisse] 
        valeurs = attributes.inject({}) { |hash, item| hash[item] = t.send(item); hash }
        valeurs[:date] = valeurs[:date].strftime("%d/%m/%y")
        # les colonnes sont: journal, date, compte, pièce, crédit, débit
 	      ligne = []
        ligne[0] = [ 'AC', valeurs[:date], 531, valeurs[:numéro], valeurs[:totalTTC], 0 ]
        ligne[1] = [ 'AC', valeurs[:date], 707, valeurs[:numéro], 0, valeurs[:ht20] ]
        ligne[2] = [ 'AC', valeurs[:date], 44571101, valeurs[:numéro], 0, valeurs[:tva20] ]
        ligne[3] = [ 'AC', valeurs[:date], 707, valeurs[:numéro], 0, valeurs[:ht5] ]
        ligne[4] = [ 'AC', valeurs[:date], 4457111, valeurs[:numéro], 0, valeurs[:tva5] ]

        # s'il n'y a pas de trou de caisse, on n'écrit aucune ligne
        # parce qu'EBP n'accepte pas d'importer des lignes avec un montant à 0
        if valeurs[:trou_de_caisse] != 0
          # si le trou de caisse est négatif, la valeur doit aller au crédit en ligne 5 et débit ligne 6, sinon l'inverse
          tab = [valeurs[:trou_de_caisse].abs, 0]
          # si le trou de caisse est négatif le compte doit être 658, et s'il est positif 758
          compte_trou_de_caisse = 658
          if valeurs[:trou_de_caisse] > 0 
            # inversion des valeurs du tableau. y'a sûrement plus joli…
           tab.push(tab[0])
           tab.delete_at(0) 
           compte_trou_de_caisse = 758
          end
  
          ligne[5] = [ 'OD', valeurs[:date], compte_trou_de_caisse, valeurs[:numéro], tab[0], tab[1] ]
          ligne[6] = [ 'OD', valeurs[:date], 531, valeurs[:numéro], tab[1], tab[0] ]

        end

        ligne.each do |l|
          csv << l
        end

      end



    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

  def index
    @all_tickets = Ticket.all
    respond_to do |format|
      format.csv { send_data @all_tickets.to_csv, filename: "tickets_mois.csv" }
    end
  end

  def show
    @ticket = Ticket.find(params[:id])
  end
  
  def new
    if Ticket.last
      @lastticket = Ticket.last 
      @date_dernier_ticket = @lastticket.date
    else
      @date_dernier_ticket = Date.today - 1.day
    end
    @newticket = Ticket.new(:date_par_défaut => prochain_jour_ouvert(@date_dernier_ticket))
  end

  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.date = Date.civil(params[:date][:year].to_i, params[:date][:month].to_i, params[:date][:day].to_i)
    if @ticket.save
      # redirect_to ticket_url(@ticket)    anciennement la page du ticket créé, changé pour rediriger vers la page new
      redirect_to new_ticket_url
    end
  end

  def ticket_params
    params.require(:ticket).permit(:numéro, :date, :ttc20, :ttc5, :caisseréelle)
  end

  
  # le prochain jour où le café est ouvert
  def prochain_jour_ouvert(datein)
    if datein.saturday?
      datein + 3.day
    elsif datein.sunday?
      datein + 2.day
    else
      datein + 1.day
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Compta du 3C"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
  </small>
  <nav>
    <ul>
      <%= link_to "Tous les tickets en CSV", tickets_path(format: "csv") %>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Saisie de tickets de caisse", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
      <!--  <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   root_path %></li>
        <li><%= link_to "Log in", '#' %></li>          -->
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
      <% #%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/tickets/index.html.erb
je suis app/views/tickets/index.html.erb

app/views/tickets/new.html.erb
<div class="row">
  <div class="col-md-6 ">
    <p><em><b>DERNIER TICKET SAISI</b></em></p>
    <!-- s'il n'y a aucun ticket encore, on n'affiche rien -->
    <% if @lastticket -%>
      <!-- wah comme c'est moche ! espacement à faire en css    -->
      <p>Numéro:&nbsp;&nbsp;&nbsp;<%= @lastticket.numéro %></p>
      <p>Date des ventes:&nbsp;&nbsp;&nbsp;<%= I18n.localize(@lastticket.date, format: "%A %d/%m/%Y") %></p>
      <p>ttc20:&nbsp;&nbsp;&nbsp;<%= sprintf("%05.2f", @lastticket.ttc20) %></p>
      <p>ttc5:&nbsp;&nbsp;&nbsp;<%= sprintf("%05.2f", @lastticket.ttc5) %></p>
      <p>Caisse réelle:&nbsp;&nbsp;&nbsp;<%= sprintf("%05.2f", @lastticket.caisseréelle) %></p>
      <p>trou de caisse:&nbsp;&nbsp;&nbsp;<%= sprintf("%+05.2f", @lastticket.trou_de_caisse) %></p>
      
      <p>----------------</p>
      <p>tva 20:&nbsp;&nbsp;&nbsp;<%= sprintf("%05.2f", @lastticket.tva20) %></p>
      <p>tva 5:&nbsp;&nbsp;&nbsp;<%= sprintf("%04.2f", @lastticket.tva5) %></p>
      <p>total ttc:&nbsp;&nbsp;&nbsp;<%= sprintf("%05.2f", @lastticket.totalTTC) %></p>
      
      
      <%= link_to "annuler", "#", :class => "btn btn-default" %>
    <% end -%>
  </div>



  <div class="col-md-6 ">
    <p><em><b>NOUVEAU TICKET</b></em></p>
    <%= form_for(@newticket) do |t| %>
      <%= t.label "Numéro de ticket" %>
      <%= t.text_field :numéro %>

      <%= t.label "Date des ventes" %>
      <%= select_date @newticket.date_par_défaut, prefix: :date, use_two_digit_numbers: :true %>

      <%= t.label 'Montant TTC 20%' %>
      <%= t.text_field :ttc20 %>

      <%= t.label 'Montant TTC 5%' %>
      <%= t.text_field :ttc5 %>

      <%= t.label "caisse réelle"%>
      <%= t.text_field :caisseréelle %>

      <%= t.submit "créer le ticket", class: "btn btn-primary" %>
    <% end %>
  </div>


</div>

app/views/tickets/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <!-- wah comme c'est moche ! espacement à faire en css    -->
    <p>Numéro:&nbsp;&nbsp;&nbsp;<%= @ticket.numéro %></p>
    <p>Date:&nbsp;&nbsp;&nbsp;<%= @ticket.date.strftime("%d/%m/%Y") %></p>
    <p>ttc20:&nbsp;&nbsp;&nbsp;<%= sprintf("%05.2f", @ticket.ttc20) %></p>
    <p>ttc5:&nbsp;&nbsp;&nbsp;<%= sprintf("%05.2f", @ticket.ttc5) %></p>
    <p>Caisse réelle:&nbsp;&nbsp;&nbsp;<%= sprintf("%05.2f", @ticket.caisseréelle) %></p>
    <p>trou de caisse:&nbsp;&nbsp;&nbsp;<%= sprintf("%+05.2f", @ticket.trou_de_caisse) %></p>

    <p>----------------</p>
    <p>tva 20:&nbsp;&nbsp;&nbsp;<%= sprintf("%05.2f", @ticket.tva20) %></p>
    <p>tva 5:&nbsp;&nbsp;&nbsp;<%= sprintf("%04.2f", @ticket.tva5) %></p>
    <p>total ttc:&nbsp;&nbsp;&nbsp;<%= sprintf("%05.2f", @ticket.totalTTC) %></p>


    <%= link_to "annuler", "#" %>   ---   <%= link_to "saisir un autre", new_ticket_url %>  
  </div>
  <!--  <%= link_to "Tous les tickets en CSV", tickets_path(format: "csv") %>   -->
</div>